// <auto-generated />
using System;
using Demo.DbMigrator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.DbMigrator.Migrations
{
    [DbContext(typeof(CustomContext))]
    [Migration("20210321082807_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Demo.DbMigrator.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Demo.DbMigrator.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("主键");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasComment("商品数量");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("订单名");

                    b.Property<string>("OrderNum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("订单号");

                    b.Property<int>("OrderType")
                        .HasColumnType("int")
                        .HasComment("订单类型 0=未知 1=正常");

                    b.HasKey("Id");

                    b.HasIndex("OrderNum")
                        .IsUnique()
                        .HasFilter("[OrderNum] IS NOT NULL");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Demo.DbMigrator.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("主键");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("订单Id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Demo.DbMigrator.OrderItem", b =>
                {
                    b.HasOne("Demo.DbMigrator.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Demo.DbMigrator.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
