// <auto-generated />
using System;
using Demo.DbMigrator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Demo.DbMigrator.Migrations
{
    [DbContext(typeof(CustomContext))]
    [Migration("20210826073844_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Demo.DbMigrator.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasComment("");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Demo.DbMigrator.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasComment("主键");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasComment("");

                    b.HasKey("Id");

                    b.HasIndex("Tags");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Demo.DbMigrator.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("主键");

                    b.Property<string>("OrderId")
                        .HasColumnType("text")
                        .HasComment("订单Id");

                    b.HasKey("Id");

                    b.ToTable("OrderItem");
                });
#pragma warning restore 612, 618
        }
    }
}
